#!/bin/python3
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from itertools import takewhile


def fibonacci():
    """Fibonacci numbers generator."""
    yield 1
    yield 2
    i, j = 1, 2
    while True:
        i, j = j, i + j
        yield j


# print(sum([i for i in takewhile(lambda x: x < 4000000, fibonacci()) if i % 2 == 0]))
t = int(input().strip())
for _ in range(t):
    n = int(input().strip())
    print(sum([i for i in takewhile(lambda x: x < n, fibonacci()) if i % 2 == 0]))
